// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ld3ECTqaBu6RgehWnBXX18ULs-IQJHo',
    appId: '1:480165861625:web:acb6e8538456574608ea28',
    messagingSenderId: '480165861625',
    projectId: 'flutter-rpg-project-1c055',
    authDomain: 'flutter-rpg-project-1c055.firebaseapp.com',
    storageBucket: 'flutter-rpg-project-1c055.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6KfPA1QiEGnN5nKdvGvk1F_E_C8y4aho',
    appId: '1:480165861625:android:97d1199e7954e33308ea28',
    messagingSenderId: '480165861625',
    projectId: 'flutter-rpg-project-1c055',
    storageBucket: 'flutter-rpg-project-1c055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMDIoawZGyjkRZPSBIIh0_gxA3eOUpbrM',
    appId: '1:480165861625:ios:7a29976f6cba113c08ea28',
    messagingSenderId: '480165861625',
    projectId: 'flutter-rpg-project-1c055',
    storageBucket: 'flutter-rpg-project-1c055.firebasestorage.app',
    iosBundleId: 'com.example.rpgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMDIoawZGyjkRZPSBIIh0_gxA3eOUpbrM',
    appId: '1:480165861625:ios:7a29976f6cba113c08ea28',
    messagingSenderId: '480165861625',
    projectId: 'flutter-rpg-project-1c055',
    storageBucket: 'flutter-rpg-project-1c055.firebasestorage.app',
    iosBundleId: 'com.example.rpgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ld3ECTqaBu6RgehWnBXX18ULs-IQJHo',
    appId: '1:480165861625:web:b177f43582efd7e408ea28',
    messagingSenderId: '480165861625',
    projectId: 'flutter-rpg-project-1c055',
    authDomain: 'flutter-rpg-project-1c055.firebaseapp.com',
    storageBucket: 'flutter-rpg-project-1c055.firebasestorage.app',
  );

}